version: "3"
services:
  protonbridge:
    image: ganeshlab/protonmail-bridge:latest
    container_name: protonmail-bridge
    restart: unless-stopped
    volumes:
      - '/path/to/data:/root'
    ports:
      - '1025:25/tcp'
      - '1143:143/tcp'  
